### ISSUE TITLE
TODO from the first run

### ISSUE THREAD

**Issue by darix** [openSUSE/packaging-workshop-2015#8]
- [x] fixing indentation for some pre (part 2)
- [x] fix mbranch example
- [ ] add single mbranch example
- [ ] explain shared library policy in more details
- [ ] script order in upgrade
- [ ] subpackage preamble
- [ ] fix typos
- [ ] when and how to split a package
- [ ] mention quilt
- [ ] osc tips & tricks
  - [ ] osc build -p/-k | osc chroot | osc lbl | osc build -x
